//Cronograma list
export enum EnumCronogramaActions {
    FETCH_CRONOGRAMAS = 'FETCH_CRONOGRAMAS',
    FETCH_CRONOGRAMAS_SUCCESS = 'FETCH_CRONOGRAMAS_SUCCESS',
    FETCH_CRONOGRAMAS_FAILURE = 'FETCH_CRONOGRAMAS_FAILURE',

    FETCH_CRONOGRAMA = 'FETCH_CRONOGRAMA',
    FETCH_CRONOGRAMA_SUCCESS = 'FETCH_CRONOGRAMA_SUCCESS',
    FETCH_CRONOGRAMA_FAILURE = 'FETCH_CRONOGRAMA_FAILURE',

    //Create new cronograma
    CREATE_CRONOGRAMA = 'CREATE_CRONOGRAMA',
    CREATE_CRONOGRAMA_SUCCESS = 'CREATE_CRONOGRAMA_SUCCESS',
    CREATE_CRONOGRAMA_FAILURE = 'CREATE_CRONOGRAMA_FAILURE',
}
