//Cronograma list
export enum EnumCronogramaActions {
    FETCH_CRONOGRAMAS = 'FETCH_CRONOGRAMAS',
    FETCH_CRONOGRAMAS_SUCCESS = 'FETCH_CRONOGRAMAS_SUCCESS',
    FETCH_CRONOGRAMAS_FAILURE = 'FETCH_CRONOGRAMAS_FAILURE',

    FETCH_CRONOGRAMA = 'FETCH_CRONOGRAMA',
    FETCH_CRONOGRAMA_SUCCESS = 'FETCH_CRONOGRAMA_SUCCESS',
    FETCH_CRONOGRAMA_FAILURE = 'FETCH_CRONOGRAMA_FAILURE',

    //Create new cronograma
    CREATE_CRONOGRAMA = 'CREATE_CRONOGRAMA',
    RESET_CRONOGRAMA = 'RESET_CRONOGRAMA',
    CREATE_CRONOGRAMA_SUCCESS = 'CREATE_CRONOGRAMA_SUCCESS',
    CREATE_CRONOGRAMA_FAILURE = 'CREATE_CRONOGRAMA_FAILURE',

    UPDATE_CRONOGRAMA = 'UPDATE_CRONOGRAMA',
    UPDATE_CRONOGRAMA_SUCCESS = 'UPDATE_CRONOGRAMA_SUCCESS',
    UPDATE_CRONOGRAMA_FAILURE = 'UPDATE_CRONOGRAMA_FAILURE',

    DELETE_CRONOGRAMA = 'DELETE_CRONOGRAMA',
    DELETE_CRONOGRAMA_SUCCESS = 'DELETE_CRONOGRAMA_SUCCESS',
    DELETE_CRONOGRAMA_FAILURE = 'DELETE_CRONOGRAMA_FAILURE',

    CLEAR_STATE = 'CLEAR_STATE',
    CLEAR_ERROR = 'CLEAR_ERROR',
}
