//Cronograma list
export enum EnumDisciplinaActions {
    CREATE_DISCIPLINA = 'CREATE_DISCIPLINA_CRONOGRAMAS',
    CREATE_DISCIPLINA_SUCCESS = 'CREATE_DISCIPLINA_SUCCESS',
    CREATE_DISCIPLINA_FAILURE = 'CREATE_DISCIPLINA_FAILURE',
}
